name: CI

on:
  schedule:
    - cron: '30 3 * * 1-5'
    - cron: '45 5 * * 0,6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4 

      - name: Установка Newman и Htmlextra и jq
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          sudo apt-get update && sudo apt-get install -y jq

      - name: Запуск коллекции и формирование отчета Htmlextra
        id: run_newman
        env: 
          API_BASE_URL: ${{ secrets.API_BASE_URL }} 
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          newman run "Trello_Marina.postman_collection.json" \
          -e "Environment_Trello.postman_environment.json" \
          --env-var "base_url=${API_BASE_URL}" \
          --env-var "APIKey=${API_KEY}" \
          --env-var "APIToken=${API_TOKEN}" \
          --reporters cli,htmlextra,json \
          --reporter-htmlextra-export report.html \
          --reporter-json-export summary.json

      - name: Прикрепляем отчет к тест-рану
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: Postman test report
          path: report.html, summary.json 

      - name: Build email subject
        if: always()
        id: email_subject
        run: |
          passed=$(jq '.stats.successful' summary.json)
          failed=$(jq '.stats.failed' summary.json)
          if [[ "${{ steps.run_newman.outcome }}" == "success" ]]; then
            echo "Тесты пройдены: $passed, Проваленные тесты: $failed" >> $GITHUB_ENV
          else
            echo "Тесты завершены с ошибками. Пройденные: $passed, Проваленные: $failed" >> $GITHUB_ENV
          fi     

      - name: Send mail 
        if: always()
        uses: dawidd6/action-send-mail@v6 
        with:   
          server_address: smtp.gmail.com  
          server_port: 465    
          username: ${{ secrets.EMAIL_USERNAME }}  
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ env.email_subject }}  
          body: "Тесты завершены. Подробнее в приложенном отчете."
          html_body: "Please find API test-report attached. This is an automated email."
          to: nedinamarina@gmail.com
          from: NedinaMarina
          attachments: report.html