name: CI (scheduled run)

on:
  schedule:
    - cron:  '30 3 * * 1-5'
    - cron:  '45 5 * * 6-7'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4 

      - name: Установка Newman и Htmlextra
        run: |
          $ npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Запуск коллекции и формаривание отчета Htmlextra
        run: newman run C:\Users\79527\Desktop\git_ptojectis\Trello_API_Testing\Trello_Marina.postman_collection.json -e C:\Users\79527\Desktop\git_ptojectis\Trello_API_Testing\Environment_Trello.postman_environment.json -r htmlextra    
      
          
