name: CI (scheduled run)

on:
  schedule:
    - cron:  '30 3 * * 1-5'
    - cron:  '45 5 * * 0,6'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4 

      - name: Установка Newman и Htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Запуск коллекции и формирование отчета Htmlextra
        env: 
          API_BASE_URL: ${{ secrets.API_BASE_URL}} 
          API_TOKEN: ${{ secrets.API_TOKEN}}
          API_KEY: ${{ secrets.API_KEY}}
        run: |
          newman run "Trello_Marina.postman_collection.json" \
          -e "Environment_Trello.postman_environment.json" \
          --env-var "base_url=${API_BASE_URL}" \
          --env-var "APIKey=${API_KEY}" \
          --env-var "APIToken=${API_TOKEN}" \
          --reporters cli,htmlextra --reporter-htmlextra-export report.html

      - name: Прикрепляем отчет к тест-рану
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: Postman test report
          path: report.html 

      - name: Проверка файлов
        if: always()
        run: ls     
      
          
